# Generated by Django 6.0.4 on 2026-04-30 14:09

import apps.cores.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('utilisateurs', '0003_alter_utilisateur_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=apps.cores.utils.generer_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('RECUE', 'Reçue'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('LIVRAISON_EN_COURS', 'Livraison en cours'), ('LIVREE', 'Livrée'), ('RECUPEREE', 'Récupérée')], default='RECUE', max_length=20)),
                ('mode_recuperation', models.CharField(choices=[('LIVRAISON_DOMICILE', 'Livraison à domicile'), ('RETRAIT_SUR_PLACE', 'Retrait sur place')], max_length=50)),
                ('heure_retrait', models.CharField(blank=True, default='', max_length=50)),
                ('delai_estime', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='utilisateurs.client')),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_preparees', to='utilisateurs.serveur')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.UUIDField(default=apps.cores.utils.generer_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantite', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True, default='')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='catalogue.plat')),
            ],
            options={
                'verbose_name': 'Ligne Commande',
                'verbose_name_plural': 'Lignes Commandes',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.UUIDField(default=apps.cores.utils.generer_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mises_a_jour', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='utilisateurs.client')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.UUIDField(default=apps.cores.utils.generer_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('instruction', models.TextField(blank=True, default='')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_paniers', to='catalogue.plat')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='commandes.panier')),
            ],
            options={
                'verbose_name': 'LignePanier',
                'verbose_name_plural': 'Ligne de Panier',
            },
        ),
    ]
