# Generated by Django 6.0.4 on 2026-04-30 14:18

import apps.cores.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=apps.cores.utils.generer_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('montant', models.PositiveIntegerField()),
                ('moyen', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=30)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=30)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
