# Generated by Django 6.0.4 on 2026-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_administrateur_client_livreur_serveur_vendeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='reference',
            field=models.CharField(editable=False, help_text='Reference metier', max_length=30, unique=True),
        ),
    ]
