# Generated by Django 6.0.4 on 2026-04-30 13:18

import apps.cores.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMenu',
            fields=[
                ('id', models.UUIDField(default=apps.cores.utils.generer_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=255, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.UUIDField(default=apps.cores.utils.generer_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('disponibilite', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('STOCK_LIMITE', 'Stock limité'), ('EPUISE', 'Épuisé')], default='DISPONIBLE', max_length=20)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plats', to='catalogue.categoriemenu')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
            },
        ),
        migrations.CreateModel(
            name='OptionPersonnalisation',
            fields=[
                ('id', models.UUIDField(default=apps.cores.utils.generer_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('type', models.CharField(choices=[('QUANTITE_ATTIEKE', 'Quantité attiéké'), ('TYPE_POISSON', 'Type de poisson'), ('ACCOMPAGNEMENT', 'Accompagnement'), ('BOISSON', 'Boisson')], max_length=30)),
                ('prix_supplement', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalogue.plat')),
            ],
            options={
                'verbose_name': 'Option Personnalisation',
                'verbose_name_plural': 'Option Personnalisations',
            },
        ),
    ]
