# Generated by Django 6.0.4 on 2026-04-30 14:28

import apps.cores.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('utilisateurs', '0003_alter_utilisateur_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.UUIDField(default=apps.cores.utils.generer_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('telphone_client', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ECHOUEE', 'Échouée')], default='EN_ATTENTE', max_length=20)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='utilisateurs.livreur')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
    ]
