# Generated by Django 6.0.4 on 2026-06-09 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('utilisateurs', '0003_alter_utilisateur_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_preparees', to='utilisateurs.serveur'),
        ),
    ]
