# Generated by Django 6.0.4 on 2026-06-09 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_lignecommande_prix_unitaire_alter_commande_serveur'),
        ('utilisateurs', '0003_alter_utilisateur_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='utilisateurs.adresselivraison'),
        ),
    ]
